name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:

# '@iframe_test'
# '@todo_smoke'
# '@todo_regression'
# '@api_test'
# '@mock_api_test'

  Todo_Smoke_Tests:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --grep @todo_smoke
      - name: Create report directory
        run: mkdir -p playwright-report-Todo-Smoke
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-Todo-Smoke
          path: playwright-report-Todo-Smoke/
          retention-days: 30

  Todo_Regression_Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep @todo_regression
    - name: Create report directory
      run: mkdir -p playwright-report-Todo-Regression
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-Todo-Regression
        path: playwright-report-Todo-Regression/
        retention-days: 30
  
  iFrame_Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep @iframe_test
    - name: Create report directory
      run: mkdir -p playwright-report-iFrame
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-iFrame
        path: playwright-report-iFrame/
        retention-days: 30  
        
  API_Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep @api_test
    - name: Create report directory
      run: mkdir -p playwright-report-API
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-API
        path: playwright-report-API/
        retention-days: 30
    
  Mock_API_Tests:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --grep @mock_api_test
      - name: Create report directory
        run: mkdir -p playwright-report-Mock-API
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-Mock-API
          path: playwright-report-Mock-API/
          retention-days: 30
