name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:

# '@iframe_test'
# '@todo_smoke'
# '@todo_regression'
# '@api_test'
# '@mock_api_test'

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['@iframe_test', '@todo_smoke', '@todo_regression', '@api_test', '@mock_api_test']
    name: Playwright Tests - ${{ matrix.tag }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep ${{ matrix.tag }}  

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.tag }}
        path: playwright-report/
        retention-days: 30        

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        # add unique identifier to artifact name to prevent overwriting when multiple jobs upload with the same name
        name: blob-report-${{ matrix.tag }}
        path: blob-report/
        retention-days: 30        

  merge-reports:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Download All Blob Reports
      uses: actions/download-artifact@v4
      with:
        path: blob-report/
    
    - name: Merge into HTML report
      run: npx playwright merge-reports --reporter html ./blob-report/

    - name: Upload Merged Report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}   
        path: playwright-report/
        retention-days: 30 